### ISSUE TITLE
Content error, Learn X in Y minutes, X = GO, ZH-CN

### ISSUE THREAD

**Issue by SlimeNull** [adambard/learnxinyminutes-docs#4208]
The title:
    "Y = GO" // wrong, should be "X = GO"

**Comment by inkydragon** [comment]
This is a site template issue, not go

But it's very strange, deployed version do not match the template

```yml
zh_cn:
  title: Y分钟速成X
  where: 其中 X=
```
https://github.com/adambard/learnxinyminutes-site/blob/master/data/i18n.yaml#L45-L47
